#!/usr/bin/env bash
#Create file and SIGTERM/SIGINT Script

echo $$ > /var/run/myscript.pid

trap "echo 'Y U no love me?!'" 2 exit
trap "echo 'I hate the kill command'" 15 exit
trap "rm /var/run/myscript.pid | pkill -9 -f 10-process_and_pid_file" 3 15 exit

x=0

while [ $x -lt 1 ]
do
	echo "To infinity and beyond"
done
