#!/usr/bin/env bash
# Manage summoned daemon

case "$1" in
	start)
		bash manage_my_process & 
		echo $$ > /var/run/my_process.pid 
		echo "manage_my_process started"
		;;
	stop)
		pkill -9 -f manage_my_process 
		rm /var/run/my_process.pid 
		echo "manage_my_process stopped"
		;;
	restart)
		pkill -9 -f manage_my_process
		rm /var/run/my_process.pid 
		bash manage_my_process & 
		echo $$ > /var/run/my_process.pid 
		echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		exit 1
		;;
esac

exit 0
